index:
    path: /
    controller: App\Controller\HomepageController::index

register:
    path: /registration
    controller: App\Controller\HomepageController::registerpage

login:
    path: /login
    controller: App\Controller\UserController::login

forgetPassword:
    path: /forgetpassword
    controller: App\Controller\HomepageController::forgetPasswordPage

logout:
    path: /logout

profile:
    path: /profile
    controller: App\Controller\HomepageController::profilepage

profileRank:
    path: /profile/rank
    controller: App\Controller\HomepageController::profileRankPage

profilePassword:
    path: /profile/password
    controller: App\Controller\HomepageController::profilePasswordPage

videos:
    path: /videos
    controller: App\Controller\HomepageController::videosPage

videoNew:
    path: /videos/new
    controller: App\Controller\HomepageController::newVideoPage

video:
    path: /videos/{videoId}
    controller: App\Controller\HomepageController::videoPage
    defaults:
        videoId: 0

game:
    path: /games
    controller: App\Controller\HomepageController::gamesPage

gameNew:
    path: /games/new
    controller: App\Controller\HomepageController::newGamePage