index:
    path: /
    controller: App\Controller\HomepageController::index

registerpage:
    path: /registration
    controller: App\Controller\HomepageController::registerpage

profilepage:
    path: /profile
    controller: App\Controller\HomepageController::profilepage