index:
    path: /
    controller: App\Controller\HomepageController::index

register:
    path: /registration
    controller: App\Controller\HomepageController::registerpage

login:
    path: /login
    controller: App\Controller\UserController::login

forgetPassword:
    path: /forgetpassword
    controller: App\Controller\HomepageController::forgetPasswordPage

logout:
    path: /logout

video:
    path: /videos
    controller: App\Controller\HomepageController::Videospage

profile:
    path: /profile
    controller: App\Controller\HomepageController::profilepage

profileRank:
    path: /profile/rank
    controller: App\Controller\HomepageController::profileRankPage

profilePassword:
    path: /profile/password
    controller: App\Controller\HomepageController::profilePasswordPage

videoNew:
    path: /videos/new
    controller: App\Controller\HomepageController::newVideoPage

