index:
    path: /
    controller: App\Controller\HomepageController::index

registerpage:
    path: /registration
    controller: App\Controller\HomepageController::registerpage

profilepage:
    path: /profile/
    controller: App\Controller\HomepageController::profilepage

logout:
    path: /logout

video:
    path: /videos
    controller: App\Controller\HomepageController::Videospage


profilerankpage:
    path: /profile/rank
    controller: App\Controller\HomepageController::profileRankPage

login:
    path: /login
    controller: App\Controller\UserController::login